console.log('time to get tf out')
console.log('its the last wedding')
console.log('you wont have to deal with this anymore')
console.log('just walk away from it all for good')
console.log('very great things are in your future')
